#!/usr/bin/env python3
"""Generate AGENTS.md from the live repository tree.

Discover Make targets from the root Makefile and SystemVerilog modules from
RTL under ips/*/rtl and top/rtl. Never hand-maintain AGENTS.md.

Usage:
  python3 scripts/gen_agent_docs.py          # write AGENTS.md
  python3 scripts/gen_agent_docs.py --check  # exit non-zero if stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
AGENTS_PATH = ROOT / "AGENTS.md"

TARGET_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):", re.MULTILINE)
MODULE_RE = re.compile(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_]*)\b", re.MULTILINE)


def discover_targets(makefile: Path) -> list[str]:
    text = makefile.read_text(encoding="utf-8")
    # Skip private / pattern-like targets; keep public phony-style names.
    found = TARGET_RE.findall(text)
    # Preserve first-seen order, unique.
    seen: set[str] = set()
    ordered: list[str] = []
    for t in found:
        if t.startswith(".") or t in seen:
            continue
        # Skip make automatic/internal helper target names if any
        if t in ("PHONY",):
            continue
        seen.add(t)
        ordered.append(t)
    return ordered


def discover_modules() -> list[tuple[str, str]]:
    modules: list[tuple[str, str]] = []
    rtl_roots = [ROOT / "ips", ROOT / "top"]
    files: list[Path] = []
    for root in rtl_roots:
        if not root.exists():
            continue
        files.extend(sorted(root.rglob("*.sv")))
        files.extend(sorted(root.rglob("*.v")))
    for path in files:
        # Synthesizable RTL: classic ips/*/rtl and top/rtl trees, plus
        # per-IP CSR modules (ips/<ip>/csr_<ip>.v) and top/address_decode.v.
        parts = path.parts
        name = path.name
        under_rtl = "rtl" in parts
        is_csr = name.startswith("csr_") and name.endswith((".v", ".sv"))
        is_addr_decode = name in ("address_decode.v", "address_decode.sv")
        if not (under_rtl or is_csr or is_addr_decode):
            continue
        text = path.read_text(encoding="utf-8")
        for match in MODULE_RE.finditer(text):
            rel = path.relative_to(ROOT).as_posix()
            modules.append((match.group(1), rel))
    # Unique by module name, stable order
    seen: set[str] = set()
    unique: list[tuple[str, str]] = []
    for name, rel in modules:
        if name in seen:
            continue
        seen.add(name)
        unique.append((name, rel))
    return unique


def render(targets: list[str], modules: list[tuple[str, str]]) -> str:
    lines: list[str] = []
    lines.append("# Agent Instructions — Dashcam SoC")
    lines.append("")
    lines.append("<!-- AUTO-GENERATED by scripts/gen_agent_docs.py — do not edit. -->")
    lines.append("")
    lines.append("This file is generated from the live repository tree.")
    lines.append("Regenerate with `python3 scripts/gen_agent_docs.py`.")
    lines.append("Staleness is checked by `make lint` via `--check`.")
    lines.append("")
    lines.append("## Project")
    lines.append("")
    lines.append("- Top module: `dashcam_soc_top`")
    lines.append("- Verification flow: `verilator_smoke`")
    lines.append("- Bus: Wishbone B4")
    lines.append("- CSR window: `0x1000_0000`")
    lines.append("- SRAM window: `0x2000_0000`")
    lines.append("- `USE_CPU` selects external Wishbone master (default) or picoRV32")
    lines.append("- Synthesis is PDK-free (Sky130 is collateral only)")
    lines.append("")
    lines.append("## Make targets")
    lines.append("")
    if not targets:
        lines.append("_No targets discovered._")
    else:
        for t in targets:
            lines.append(f"- `{t}`")
    lines.append("")
    lines.append("## Self-check contract")
    lines.append("")
    lines.append("From the repository root, all of the following must exit 0:")
    lines.append("")
    lines.append("```")
    lines.append("make regs && make lint && make sim && make sw && make synth")
    lines.append("```")
    lines.append("")
    lines.append("## RTL modules")
    lines.append("")
    if not modules:
        lines.append("_No modules discovered._")
    else:
        lines.append("| Module | File |")
        lines.append("|--------|------|")
        for name, rel in modules:
            lines.append(f"| `{name}` | `{rel}` |")
    lines.append("")
    lines.append("## Layout")
    lines.append("")
    lines.append("- `ips/<block>/rtl/` — IP block RTL stubs")
    lines.append("- `top/rtl/` — chip top")
    lines.append("- `dv/sim/verilator_smoke/` — smoke harness")
    lines.append("- `sw/` — firmware")
    lines.append("- `csv/` — register address-map source of truth (`register_spec.csv`)")
    lines.append("- `include/` — generated SystemRDL (`*_csr.rdl`) and Verilog CSR defines")
    lines.append("- `scripts/` — generators (`reggen.py`, `csv_validation.py`, `gen_agent_docs.py`)")
    lines.append("- `docs/` — prose / generated register map (Markdown + SystemRDL)")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate AGENTS.md from the tree")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if AGENTS.md is missing or stale",
    )
    args = parser.parse_args(argv)

    makefile = ROOT / "Makefile"
    if not makefile.exists():
        print("error: Makefile not found", file=sys.stderr)
        return 1

    content = render(discover_targets(makefile), discover_modules())

    if args.check:
        if not AGENTS_PATH.exists():
            print("error: AGENTS.md missing — run scripts/gen_agent_docs.py", file=sys.stderr)
            return 1
        existing = AGENTS_PATH.read_text(encoding="utf-8")
        if existing != content:
            print("error: AGENTS.md is stale — run scripts/gen_agent_docs.py", file=sys.stderr)
            return 1
        print("gen_agent_docs: AGENTS.md is up to date")
        return 0

    AGENTS_PATH.write_text(content, encoding="utf-8")
    print(f"gen_agent_docs: wrote {AGENTS_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
