#!/usr/bin/env python3
"""Register-map generator (Python 3 stdlib only).

Reads scripts/regs.json and generates:
  - sw/include/<block>_regs.h  (per-IP CSR headers)
  - docs/register_map.md       (markdown register map)

Output is deterministic: running twice changes nothing.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SPEC = Path(__file__).resolve().parent / "regs.json"
SW_INCLUDE = ROOT / "sw" / "include"
DOCS = ROOT / "docs"


def parse_int(value: str | int) -> int:
    if isinstance(value, int):
        return value
    return int(str(value), 0)


def field_mask(bits: str) -> tuple[int, int, int]:
    """Return (msb, lsb, mask) for a field bit range string."""
    bits = bits.strip()
    if ":" in bits:
        msb_s, lsb_s = bits.split(":", 1)
        msb, lsb = int(msb_s), int(lsb_s)
    else:
        msb = lsb = int(bits)
    if msb < lsb:
        msb, lsb = lsb, msb
    width = msb - lsb + 1
    mask = ((1 << width) - 1) << lsb
    return msb, lsb, mask


def load_spec(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def gen_header(block: dict) -> str:
    name = block["name"].upper()
    base = parse_int(block["base"])
    lines: list[str] = []
    lines.append(f"#ifndef {name}_REGS_H_")
    lines.append(f"#define {name}_REGS_H_")
    lines.append("")
    lines.append(f"/* Auto-generated by scripts/reggen.py — do not edit. */")
    lines.append(f"/* Block: {block['name']} — {block.get('description', '')} */")
    lines.append("")
    lines.append(f"#define {name}_BASE 0x{base:08X}u")
    lines.append("")
    for reg in block["registers"]:
        offset = parse_int(reg["offset"])
        rname = reg["name"].upper()
        lines.append(f"#define {name}_{rname}_OFFSET 0x{offset:X}u")
        lines.append(f"#define {name}_{rname}_ADDR ({name}_BASE + {name}_{rname}_OFFSET)")
        for field in reg.get("fields", []):
            fname = field["name"].upper()
            msb, lsb, mask = field_mask(field["bits"])
            lines.append(f"#define {name}_{rname}_{fname}_LSB {lsb}")
            lines.append(f"#define {name}_{rname}_{fname}_MSB {msb}")
            lines.append(f"#define {name}_{rname}_{fname}_MASK 0x{mask:08X}u")
        lines.append("")
    lines.append(f"#endif /* {name}_REGS_H_ */")
    lines.append("")
    return "\n".join(lines)


def gen_markdown(spec: dict) -> str:
    lines: list[str] = []
    lines.append(f"# {spec.get('title', 'Register Map')}")
    lines.append("")
    lines.append("Auto-generated by `scripts/reggen.py` — do not edit.")
    lines.append("")
    lines.append(f"- Bus: **{spec.get('bus', 'Wishbone')}**")
    lines.append(f"- CSR window: `{spec.get('csr_window_base', '0x10000000')}`")
    lines.append(f"- SRAM window: `{spec.get('sram_window_base', '0x20000000')}`")
    lines.append("")
    for block in spec["blocks"]:
        base = parse_int(block["base"])
        lines.append(f"## {block['name']} @ `0x{base:08X}`")
        lines.append("")
        if block.get("description"):
            lines.append(block["description"])
            lines.append("")
        lines.append("| Offset | Name | Access | Reset | Description |")
        lines.append("|--------|------|--------|-------|-------------|")
        for reg in block["registers"]:
            offset = parse_int(reg["offset"])
            lines.append(
                f"| `0x{offset:02X}` | `{reg['name']}` | {reg.get('access', 'rw')} "
                f"| `{reg.get('reset', '0x0')}` | {reg.get('description', '')} |"
            )
        lines.append("")
        for reg in block["registers"]:
            fields = reg.get("fields", [])
            if not fields:
                continue
            lines.append(f"### {reg['name']}")
            lines.append("")
            lines.append("| Bits | Name | Access | Description |")
            lines.append("|------|------|--------|-------------|")
            for field in fields:
                lines.append(
                    f"| `{field['bits']}` | `{field['name']}` | {field.get('access', 'rw')} "
                    f"| {field.get('description', '')} |"
                )
            lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return False
    path.write_text(content, encoding="utf-8")
    return True


def generate(spec_path: Path) -> int:
    spec = load_spec(spec_path)
    changed = 0
    for block in sorted(spec["blocks"], key=lambda b: b["name"]):
        header = gen_header(block)
        out = SW_INCLUDE / f"{block['name']}_regs.h"
        if write_if_changed(out, header):
            changed += 1
            print(f"reggen: wrote {out.relative_to(ROOT)}")
        else:
            print(f"reggen: unchanged {out.relative_to(ROOT)}")
    md = gen_markdown(spec)
    md_path = DOCS / "register_map.md"
    if write_if_changed(md_path, md):
        changed += 1
        print(f"reggen: wrote {md_path.relative_to(ROOT)}")
    else:
        print(f"reggen: unchanged {md_path.relative_to(ROOT)}")
    print(f"reggen: done ({changed} file(s) updated)")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Dashcam SoC register-map generator")
    parser.add_argument(
        "-i",
        "--input",
        type=Path,
        default=DEFAULT_SPEC,
        help="Register description JSON (default: scripts/regs.json)",
    )
    args = parser.parse_args(argv)
    if not args.input.exists():
        print(f"error: missing register spec {args.input}", file=sys.stderr)
        return 1
    return generate(args.input)


if __name__ == "__main__":
    sys.exit(main())
