#ifndef CSR_REGS_H_
#define CSR_REGS_H_

/* Aggregated CSR register map for Dashcam SoC firmware.
 * Per-block headers are generated by scripts/reggen.py into sw/include/.
 */

#include "cam_regs.h"
#include "dma_regs.h"
#include "irq_regs.h"
#include "iomux_regs.h"
#include "sdspi_regs.h"

/* Memory map windows (Wishbone). */
#define CSR_WINDOW_BASE  0x10000000u
#define SRAM_WINDOW_BASE 0x20000000u

#endif /* CSR_REGS_H_ */
