#ifndef IOMUX_REGS_H_
#define IOMUX_REGS_H_

/* Auto-generated by scripts/reggen.py — do not edit. */
/* Block: iomux — I/O multiplexer */

#define IOMUX_BASE 0x10000300u

#define IOMUX_CTRL_OFFSET 0x0u
#define IOMUX_CTRL_ADDR (IOMUX_BASE + IOMUX_CTRL_OFFSET)
#define IOMUX_CTRL_SEL_LSB 0
#define IOMUX_CTRL_SEL_MSB 3
#define IOMUX_CTRL_SEL_MASK 0x0000000Fu

#endif /* IOMUX_REGS_H_ */
